FROM python:3.10-slim

RUN mkdir /app

COPY requirements.txt /app

RUN python -m pip install --upgrade pip
RUN pip3 install -r /app/requirements.txt --no-cache-dir

COPY . /app
WORKDIR /app/tgbot

CMD ["celery", "-A", "tgbot", "worker"]