# Generated by Django 4.2.2 on 2023-06-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Callback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField()),
                ("article", models.IntegerField()),
                ("interval", models.DurationField(null=True)),
                ("start_time", models.DateTimeField(null=True)),
            ],
        ),
    ]
